Model Maker: Fix CI: install libsndfile as part of the pip setup.
Currently failing for

RuntimeError: Failed to import librosa. You might be missing sndfile, which can be installed via sudo apt-get install libsndfile1 on Ubuntu/Debian.
PiperOrigin-RevId: 391058930